name: Deploy Frontend

on: 
  push:
    branches:
    - main

defaults:
  run:
    working-directory: use-mapbox-gl-js-with-react

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [10.x, 12.x, 14.x]
    steps:
    - name: Checkout Repo Code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '2.x'
    - name: Use Node.js 12.x
      uses: actions/setup-node@v3
      with:
        node-version: '12.x'
  

    - name: Install Packages
      run: npm install

    - name: Setup environment
      run: |
        echo REACT_APP_PRIVATE_MAPBOX_ACCESS_TOKEN=${{ secrets.PRIVATE_MAPBOX_ACCESS_TOKEN }} > .env

    # - name: Use Node.js 12.x
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '12.x'
    # - name: Checkout Repository Code
    #   uses: actions/checkout@v1
    # - name: Rebuild sass
    #   run: npm rebuild node-sass
    # - name: Install Packages
    #   run: npm install
    - name: Update Browser List
      run: npx browserslist@lastest --update-db
    - name: Build project
      run: npm run build
